### ISSUE TITLE
TO_EMAIL

### ISSUE THREAD

**Issue by ccarruitero** [danielwestendorf/engineering-app#6]
The app needs to define a TO_EMAIL variable to send application to the collector of applications.

So in order that applicant send you the email after fix this, you needs to provide the email that he should setup.

**Comment by danielwestendorf** [comment]
The intent is not for you to submit the application from your local machine.

**Comment by ccarruitero** [comment]
Yes, nevermind.

I found how send the application.

Btw, env vars in README are wrong like part of test?
